### ISSUE TITLE
make output type more accurate

### ISSUE THREAD

**Issue by agarwal** [agarwal/oloop#1]
We currently define `type phrase`, but the definition isn't really accurate. It assumes a separation of `stderr` and `stdout`, but actually these outputs should be interleaved. Also exceptions aren't mentioned. The correct type to represent outputs is probably something like:

``` ocaml
type output = [`Stdout of string | `Stderr of string] list * exn option
```

This captures all stdout and stderr in the order that output occurs. It also includes an exception that may have been raised.

The harder part is to:
- [x] Adjust the script to retain stdout and stderr in the order they are output.
- [x] Robustly capture any exception raised by the evaluated expression, being sure not to conflate that with exceptions raised by the code evaluating the code.
- [x] If possible, also distinguish between the output that is a rendering of the evaluated phrase vs output that is a side effect of evaluating the phrase. In this case, see if something better than `string` should be used to represent the result. Maybe some type from the Outcometree or Toploop modules.

**Comment by Chris00** [comment]
There is still the goal of capturing stdout and stderr in the right order while distinguishing them but I do not think it is easy to do—short of modifying the underlying C library but I do not think we want to do that.

**Comment by agarwal** [comment]
Closing this issue. It is essentially done, short of the last point mentioned by @Chris00 which is not a requirement at this time.
