### ISSUE TITLE
Add information of location of errors and warnings.

### ISSUE THREAD

**Issue by romildo** [agarwal/oloop#11]
When the compilation of a phrase results in a warning or an error message, add information of the location where it was detected.

**Comment by Chris00** [comment]
Not sure to understand: [Oloop.eval_error](https://github.com/agarwal/oloop/blob/master/lib/oloop.mli#L79) contains `Location.t` that indicates precisely that.

**Comment by romildo** [comment]
I am just trying applications buit with the project, like `app.native`. It does not report the location of errors.

**Comment by Chris00** [comment]
You have to understand that the app is still very much WIP so the output may still change. I did the following.  When an error occurs, a sexp representation of the location (if available) is [present in the output](https://github.com/agarwal/oloop/commit/1aeeff8343074b79047743a0aeee39050bbc5c53).  You can also use the command line option `--msg-with-location` to have the [location added to the error message](https://github.com/agarwal/oloop/commit/69b852d0e2d1d712a9b68308beacb57d75abe052).  Hope it helps.
