### ISSUE TITLE
assure duplicated type error definitions are equivalent

### ISSUE THREAD

**Issue by agarwal** [agarwal/oloop#12]
To avoid having oloop-top depend on sexplib, we avoid adding `with sexp` to the definition of `type error` in Oloop_types. However, we want the same definition in Oloop with `with sexp`. This ends up causing us to duplicate the definitions, but there is no compiler enforcement that they are identical. Is there a way to make it so? If we used regular variants, we could use manifest type:

``` ocaml
module A = struct
  type t = A | B
end

type u = A.t = A | B
with sexp
```

but the analogous idea doesn't work with polymorphic variants. This is a syntax error:

``` ocaml
module A = struct
  type t = [`A | `B]
end

type u = A.t = [`A | `B]
with sexp
```

**Comment by Chris00** [comment]
On Thu, 2 Apr 2015 15:02:31 -0700, Ashish Agarwal wrote:

> To avoid having oloop-top depend on sexplib, we avoid adding with sexp to the definition of type error in Oloop_types. However, we want the same definition in Oloop with with sexp.

This is no longer true! ;-) The definition in Oloop_types is similar but different — one needs to be able to serialize it...

**Comment by Chris00** [comment]
On Thu, 2 Apr 2015 15:02:31 -0700, Ashish Agarwal wrote:

> module A = struct
>   type t = [`A |`B]
> end
> 
> type u = A.t = [`A |`B]
> with sexp

You do not need to rexport because polymorphic variants are not
attached to the module.  To ensure that you have equality, you can use

type u = [`A |`B] as 'a constraint 'a = A.t

**Comment by agarwal** [comment]
Thanks. A type constraint is what I was looking for. But anyway this issue is now moot since the definitions are not equivalent anymore. I'll close.
