### ISSUE TITLE
improve ocaml file parser

### ISSUE THREAD

**Issue by agarwal** [agarwal/oloop#2]
Right now we represent with type `(float * string) list`, which associates part numbers with the content of that part. We probably also want to detect which phrases are directives vs regular OCaml code.

**Comment by Chris00** [comment]
Why?  I mean, if it is to [silence the directives](https://github.com/agarwal/oloop/issues/3), this is not necessary.  In any case, the directives need to end with `;;` (and thus be treated as separate phrases) or else an error will be returned.

**Comment by agarwal** [comment]
Done in 89ac6eac2094e162e9158c68054ff67ac45310e6. We don't parse out directives yet. If that does end up being needed, we can open another issue.
