### ISSUE TITLE
silent-directives still shows output

### ISSUE THREAD

**Issue by agarwal** [agarwal/oloop#20]
```
$ cat a.ml
#use "topfind";;

$ ./app.native -silent-directives a.ml
(* part 0 *)
# #use "topfind";;
Findlib has been successfully loaded. Additional directives:
  #require "package";;      to load a package
  #list;;                   to list the available packages
  #camlp4o;;                to load camlp4 (standard syntax)
  #camlp4r;;                to load camlp4 (revised syntax)
  #predicates "p,q,...";;   to set these predicates
  Topfind.reset();;         to force that packages will be reloaded
  #thread;;                 to enable threads
```

**Comment by Chris00** [comment]
On Tue, 5 May 2015 12:59:09 -0700, Ashish Agarwal wrote:

> $ cat a.ml
> #use "topfind";;
> 
> $ ./app.native -silent-directives a.ml
> (\* part 0 *)
> 
> # #use "topfind";;
> 
> Findlib has been successfully loaded. Additional directives:
>   #require "package";;      to load a package
>   #list;;                   to list the available packages
>   #camlp4o;;                to load camlp4 (standard syntax)
>   #camlp4r;;                to load camlp4 (revised syntax)
>   #predicates "p,q,...";;   to set these predicates
>   Topfind.reset();;         to force that packages will be reloaded
>   #thread;;                 to enable threads

Yes, the description says it silences the structure returned, not what is written to stdout/stderr.  One can adopt that specification if desired.

**Comment by agarwal** [comment]
Right, I see it only sets `out_phrase = Oloop_types.empty`. I'm unsure what useful structure information is ever returned by a directive. Is there a case you'd want to see this.

I do think silencing the output would also be useful. Depending on answer to above, we should either change meaning of this directive to silence output or introduce another option.

**Comment by agarwal** [comment]
Also, is there a reason to pass `silent_directives` all they way to `oloop-top`? AFAICT, we could always return the structure from that script, and implement the logic of `silent_directives` within `Oloop.eval`. Or maybe even further, it could be up to whoever calls `eval`, e.g. the command line app.

**Comment by Chris00** [comment]
On Tue, 5 May 2015 13:42:40 -0700, Ashish Agarwal wrote:

> Right, I see it only sets out_phrase = Oloop_types.empty. I'm unsure what useful structure information is ever returned by a directive. Is there a case you'd want to see this.

Possibly when you include a file.  That's why the information is shown if the directive throws an exception.

> I do think silencing the output would also be useful. Depending on answer to above, we should either change meaning of this directive to silence output or introduce another option.

I think it is OK to change the meaning of the directive.

**Comment by Chris00** [comment]
On Tue, 5 May 2015 13:49:31 -0700, Ashish Agarwal wrote:

> Also, is there a reason to pass silent_directives all they way to oloop-top?

You read my mind! ;-)

> AFAICT, we could always return the structure from that script, and implement the logic of silent_directives within Oloop.eval. Or maybe even further, it could be up to whoever calls eval, e.g. the command line app.

Right.  The only thing is that we have to decide whether the phrase is a directive or not but that information could, say, be sent back to the oloop library.

**Comment by agarwal** [comment]
> Possibly when you include a file.

Got it. Do you plan to work on this in the next day or so? Otherwise I will, but we both shouldn't as we'll just get merge conflicts.

**Comment by Chris00** [comment]
On Tue, 5 May 2015 14:27:32 -0700, Ashish Agarwal wrote:

> | Possibly when you include a file.
> 
> Got it. Do you plan to work on this in the next day or so? Otherwise I will, but we both shouldn't as we'll just get merge conflicts.

Done but untested.

**Comment by agarwal** [comment]
Thanks. This seems to all work, so closing.
