### ISSUE TITLE
-init option doesn't do anything

### ISSUE THREAD

**Issue by agarwal** [agarwal/oloop#25]
```
$ cat ocamlinit 
#use "topfind";;
#thread;;
#require "core async";;

$ utop

utop # Oloop.with_toploop ~init:"ocamlinit" Oloop.Outcome.merged ~f:(fun t -> eval t "open Core_kernel.Std" >>| fun x -> Ok x);;
- : Oloop_outcome.merged Outcome.t Core_kernel.Std.Or_error.t =
Core_kernel.Result.Ok
  (`Uneval
    (`Typetexp
       ({Location.loc_start =
          {Lexing.pos_fname = "//toplevel//"; pos_lnum = 1; pos_bol = 0; pos_cnum = 5};
         loc_end = {Lexing.pos_fname = "//toplevel//"; pos_lnum = 1; pos_bol = 0; pos_cnum = 20};
         loc_ghost = false},
        <abstr>, Typetexp.Unbound_module (Longident.Lident "Core_kernel")),
     "Error: Unbound module Core_kernel\n"))
```

It's not an issue with relative paths. Passing the absolute path to `init` doesn't change the behavior.

**Comment by agarwal** [comment]
I just pushed support for `-noinit` in 361f5229952e17267f0887f0d3df755d24a32351, and it also doesn't seem to have any effect.

In fact the behavior is the opposite of what I expected. With both `-noinit` and `-init` _not_ passed, I was expecting my default `~/.ocamlinit` file to get picked up by oloop, but it isn't.

**Comment by Chris00** [comment]
`~init:file` could simply issue a `#use "file"` (possibly searching first the `file` at standard locations).

**Comment by agarwal** [comment]
> ~init:file could simply issue a #use "file"

Yes, but I feel that's avoiding the issue, which is that command line options to `oloop-top` are not getting activated. Maybe the technique of mutating `Clflags` isn't right.

**Comment by Chris00** [comment]
Both options are used by `Toploop.load_ocamlinit`:

``` ocaml
let load_ocamlinit ppf =
  if !Clflags.noinit then ()
  else match !Clflags.init_file with
  | Some f -> if Sys.file_exists f then ignore (use_silently ppf f)
              else fprintf ppf "Init file not found: \"%s\".@." f
  | None ->
     if Sys.file_exists ".ocamlinit" then ignore (use_silently ppf ".ocamlinit")
     else try
       let home_init = Filename.concat (Sys.getenv "HOME") ".ocamlinit" in
       if Sys.file_exists home_init then ignore (use_silently ppf home_init)
     with Not_found -> ()
```

One may add this function to `oloop-top` but then the question is what we do about its possible output (indicating a problem).  Maybe it is better to add `Oloop.init` that is inspired by this function be that indicates an error through its return value?

**Comment by agarwal** [comment]
Okay, I suppose for `init` and `noinit`, it might be easiest to implement this functionality directly in oloop. Also, then we can provide `noinit` in OCaml 4.01.0 without any problem.

**Comment by Chris00** [comment]
Please test more.  The following

``` ocaml
utop # Oloop.with_toploop Oloop.Outcome.merged ~f:(fun t -> init ~init_file:"ocamlinit" t >>=? fun () -> eval t "open Core_kernel.Std" >>| fun x -> Ok x);;
```

seems to work.

**Comment by agarwal** [comment]
Ahh... I see why I'm getting merge conflicts now.  :)

**Comment by agarwal** [comment]
fafa8c09eb18176658048f2310856efdea4a2d27 does compile on both 4.01.0 and 4.02.1, but I still feel it is a hack. We've now implemented ourselves something the OCaml toplevel is supposed to already be doing.

**Comment by agarwal** [comment]
I have to go right now, but I'll do a release later so at least we get into opam.

**Comment by Chris00** [comment]
@agarwal In principle, I agree: if possible, we should use the functionality provided by the toploop library.  In this case however, the functionality is in [load_ocamlinit](https://github.com/ocaml/ocaml/blob/trunk/toplevel/toploop.ml#L439) and this function is not exported (not speaking about the need to make this code conditional since `Clflags.noinit` is only available on recent versions of OCaml).

Note that the current implementation is not without flaws either.
1. It does not report an error when there is an error in the included file.
2. The current directory of the main program may be different from the one of the toploop instance, in which case the detection of the existence of the file is bogus.

The functionality should probably be moved to `oloop-top` into a function alike `load_ocamlinit` and a special input command (i.e. make the value sent to the toploop be a variant) should trigger it.

**Comment by Chris00** [comment]
I reopen the issue so that we do not forget to find a satisfactory solution.

**Comment by agarwal** [comment]
Ok, thanks for the explanation.

**Comment by Chris00** [comment]
Hope you like the new implementation.  It handles both issues that the previous one had.
