### ISSUE TITLE
optionally silence output of directives

### ISSUE THREAD

**Issue by agarwal** [agarwal/oloop#3]
You often don't want to see the output of `#require` and other directives. Add an option to the command line app that will omit this output.

**Comment by Chris00** [comment]
The infrastructure is in place (just ignore the output of the command).  You must send `#require` commands separately anyway since `eval` will not read past `;;`.

**Comment by Chris00** [comment]
This is turned on or off when the toploop is created.  It is definitely possible to switch between the two modes in the live toploop (enriching the commands one can send to the toploop).  Is is desired?

**Comment by agarwal** [comment]
At this point, I think the current option should be sufficient.
