### ISSUE TITLE
customize which libraries are loaded and which modules are opened by default

### ISSUE THREAD

**Issue by agarwal** [agarwal/oloop#4]
Although one can always include the desired directives and module open commands in the input file, it might be convenient to pass these as command line options. For example, someone might want to always load core and async and open Core.Std and Async.Std, without having to write this at the top of their files.

**Comment by fxfactorial** [comment]
I believe this is done in 90a3809fdeb9fb0cf1becbcc8e029eff84b07874

I also added a .merlin file in a commit prior to that one.

**Comment by agarwal** [comment]
Thanks. I merged to master. I'll leave this issue open however, as I think we can get a more general solution too. We should be able to customize for libraries beyond just Core and Async.

**Comment by Chris00** [comment]
Do you always want to load `core`?  It is rather heavy (takes a noticeable time at startup) and is not necessarily needed (considering `Oloop` is a general library). @agarwal ?

**Comment by agarwal** [comment]
@Chris00 Now that oloop is much more general, no particular library should be given any special consideration. You can load Core just like anything else.
